cc_library(
    name = "index",
    copts = ["-Werror"],
    include_prefix = "indexlib/index",
    visibility = ["//visibility:public"],
    deps = [
      "//aios/storage/indexlib/indexlib:indexlib_h",
    ],
    alwayslink = True,
)
