cc_library(
  name = "indexlib_h",
  hdrs = [
  ],
  copts = ["-Werror"],
  include_prefix = "indexlib",
  visibility = ["//visibility:public"],
  deps = [
    ":indexlib_header",
  ],
)

cc_library(
  name = "indexlib_header",
  hdrs = [
    "indexlib.h",
  ],
  copts = ["-Werror"], 
  include_prefix = "indexlib",
  visibility = ["//visibility:public"],
)
